# -*- coding: utf-8 -*-
"""lab_02_pfds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaIMgiyZtdvZKSlYkIyjiVY4txk3zQlM
"""

import numpy as np

marks = np.array([
    [85, 78, 92],
    [67, 88, 75],
    [90, 94, 89],
    [76, 64, 70],
    [82, 79, 85]
])

avg_per_student = np.mean(marks, axis=1)
min_per_student = np.min(marks, axis=1)
max_per_student = np.max(marks, axis=1)

print("Marks Array:\n", marks)
print("\nAverage Marks per Student:", avg_per_student)
print("Minimum Marks per Student:", min_per_student)
print("Maximum Marks per Student:", max_per_student)

print("\nMarks of 2nd and 4th student:\n", marks[[1, 3]])

high_scorers = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in any subject:\n", marks[high_scorers])

reshaped = marks.T
print("\nReshaped Array (Subject-wise):\n", reshaped)